In [1]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
df1 = df.iloc[0:4]
print(df1)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [2]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
df1 = df.iloc[:, 0:2]

print(df1)

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [3]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)
value = df.iloc[2, 3]  
print("Specific Cell Value:", value)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000
Specific Cell Value: 8428000

In [4]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)
data = df[df['Age'] > 35].iloc[:, :] 
print("\nFiltered Data based on Age > 35:\n", data)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

Filtered Data based on Age > 35:
             Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

In [5]:
player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]
df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
df.set_index('Name', inplace=True)

custom = df.loc['A.B.D Villers':'S.Smith']
print(custom)

               Age  Weight   Salary
Name
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000

In [6]:
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [7]:
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

display(dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')),
                    ['Name','JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [8]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}

data2 = {'Name': ['Abhi', 'Ayushi', 'Dhiraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[4, 5, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

      Name  Age    Address Qualification
4    Abhi   17     Nagpur         Btech
5  Ayushi   14     Kanpur           B.A
6  Dhiraj   12  Allahabad          Bcom
7  Hitesh   52    Kannuaj        B.hons

In [9]:
import pandas as pd 
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd'],
        'Mobile No': [97, 91, 58, 76]} 
data2 = {'Name':['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'], 
        'Age':[22, 32, 12, 52], 
        'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'], 
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons'],
        'Salary':[1000, 2000, 3000, 4000]}  
df = pd.DataFrame(data1,index=[0, 1, 2, 3]) 
df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])  
print(df, "\n\n", df1)
res = pd.concat([df, df1], ignore_index=True)
res

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [10]:
res2 = pd.concat([df, df1], axis=1, join='inner')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [11]:
res2 = pd.concat([df, df1], axis=1, join='outer')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [12]:
import pandas as pd
import numpy as np

data = np.array(['g', 'e', 'e', 'k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: str

In [13]:
import pandas as pd
import numpy as np

data = np.array(['g', 'e', 'e', 'k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: str

In [14]:
import pandas as pd
import numpy as np

data = np.array(['g', 'e', 'e', 'k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: str

In [15]:
import pandas as pd
data_dict = {'Geeks': 10, 'for': 20, 'geeks': 30}

ser = pd.Series(data_dict)
print(ser)

Geeks    10
for      20
geeks    30
dtype: int64

In [16]:
import numpy as np
import pandas as pd
ser = pd.Series(np.linspace(1, 10, 5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [17]:
import pandas as pd
ser = pd.Series(range(5, 15))
print(ser)

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

In [18]:
import pandas as pd
import numpy as np
data = np.array(['g', 'e', 'e', 'k', 's', 'f',
                 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)
print(ser[0])

g

In [19]:
import pandas as pd
import numpy as np
data = np.array(['g', 'e', 'e', 'k', 's', 'f',
                 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)
print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: str

In [22]:
import pandas as pd
df = pd.read_csv("heart.csv")
ser = pd.Series(df['Year'])
ser.head(5)

0    2024
1    2024
2    2024
3    2024
4    2024
Name: Year, dtype: int64

In [23]:
import pandas as pd
import numpy as np
data = np.array(['g', 'e', 'e', 'k', 's', 'f',
                 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data, index=[10, 11, 12, 13, 14,
                             15, 16, 17, 18, 19, 20, 21, 22])
print(ser[16])

o

In [24]:
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
result = s1 + s2
print(result)

a    11
b    22
c    33
dtype: int64

In [25]:
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
result = s1==s2
print(result)

a    False
b    False
c    False
dtype: bool

In [26]:
df1 = pd.DataFrame({'A': [10, 20, 30], 'B': [40, 50, 60]})
df2 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
result = df1 - df2
print(result)

    A   B
0   9  36
1  18  45
2  27  54

In [27]:
import pandas as pd
import numpy as np
data = np.array(['a', 'b', 'c', 'd', 'e'])
s = pd.Series(data, index=[1000, 1001, 1002, 1003, 1004])
print(s)

1000    a
1001    b
1002    c
1003    d
1004    e
dtype: str

In [28]:
import pandas as pd
import numpy as np
data = np.array(['a', 'b', 'c', 'd', 'e'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
4    e
dtype: str

In [29]:
import pandas as pd
Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
idx_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']
sr = pd.Series(data = Date,        
              index = idx_name)
sr.reset_index(drop=True, inplace=True)
print(sr)

0    1/1/2018
1    2/1/2018
2    3/1/2018
3    4/1/2018
dtype: str

In [30]:
import pandas as pd

series = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon'])

series.index = ['City 1', 'City 1', 'City 3', 'City 3'] 
print(series)

City 1    New York
City 1     Chicago
City 3     Toronto
City 3      Lisbon
dtype: str

In [32]:
import pandas as pd
import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
mv = df.isnull()
print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [33]:
import pandas as pd
import numpy as np
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}
df = pd.DataFrame(data)
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [34]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
nmv = df.notnull()
print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [36]:
d = pd.read_csv("employees.csv")
nmg = pd.notnull(d["Gender"])
nmgd= d[nmg]
display(nmgd)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [37]:
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [38]:
df.ffill()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [40]:
df.bfill()

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [41]:
import pandas as pd
import numpy as np
d = pd.read_csv("employees.csv")
d["Gender"] = d["Gender"].fillna('No Gender')
d[10:25]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No Gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [42]:
import pandas as pd
import numpy as np
data = pd.read_csv("employees.csv")
data[10:25]
data.replace(to_replace=np.nan, value=-99)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,-99
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,-99,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [43]:
import pandas as pd
import numpy as np
data = {'Score': [10, np.nan, 30, np.nan, 50]}
df = pd.DataFrame(data)
df['Score'] = df['Score'].interpolate()
print(df)

   Score
0   10.0
1   20.0
2   30.0
3   40.0
4   50.0

In [44]:
import pandas as pd 
df = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
k=df.interpolate(method ='linear', limit_direction ='forward')
print(df)
print(k)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0
      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

In [45]:
import pandas as pd
import numpy as np
dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna()

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [46]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna(how='all')

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
1          NaN           NaN          NaN           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

In [47]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, np.nan, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)
print(df)
df.dropna(axis=0)   
df.dropna(axis=0)

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0            60
1          NaN           NaN          NaN            67
2          NaN           NaN         80.0            68
3         95.0          56.0         98.0            65

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0            60
3         95.0          56.0         98.0            65

In [48]:
import pandas as pd
d = pd.read_csv("employees.csv")
nd = d.dropna(axis=0, how='any')
print("Old data frame length:", len(d))
print("New data frame length:", len(nd))
print("Rows with at least one missing value:", (len(d) - len(nd)))

Old data frame length: 1000
New data frame length: 764
Rows with at least one missing value: 236

In [49]:
import pandas as pd
data = {"Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
df_cleaned = df.drop_duplicates()
print("\nModified DataFrame (no duplicates)")
print(df_cleaned)

Original DataFrame:
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

Modified DataFrame (no duplicates)
    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [50]:
import pandas as pd
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'SF', 'Chicago']})
df_cleaned = df.drop_duplicates(subset=["Name"])
print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [51]:
import pandas as pd
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']})
df_cleaned= df.drop_duplicates(keep='last')
print(df_cleaned)

    Name  Age     City
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

In [52]:
import pandas as pd
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'], 'Age': [25, 30, 25, 40],'City': ['NY', 'LA', 'NY', 'Chicago']})
df_cleaned = df.drop_duplicates(keep=False)
print(df_cleaned)

    Name  Age     City
1    Bob   30       LA
3  David   40  Chicago

In [53]:
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Alice', 'David'],'Age': [25, 30, 25, 40],'City': ['NY', 'LA', 'NY', 'Chicago']})
df.drop_duplicates(inplace=True)
print(df)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [54]:
import pandas as pd
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 'Age': [25, 30, 22, 35, 28], 'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 'Salary': [50000, 55000, 40000, 70000, 48000]}
df = pd.DataFrame(data)
print(df.dtypes)
df['Age'] = df['Age'].astype(float)
print(df.dtypes)

Name        str
Age       int64
Gender      str
Salary    int64
dtype: object
Name          str
Age       float64
Gender        str
Salary      int64
dtype: object

In [55]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'], "Gender": ["", "", ""],"Age": [0, 0, 0]})
df['Department'] = np.nan
print(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

In [56]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],"Gender": ["", "", ""], "Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
df.dropna(how='all', axis=1, inplace=True)
display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age
0     Vipul           0
1    Ashish           0
2     Milan           0

In [57]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],"Gender": ["", "", ""],"Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
nan_value = float("NaN")
k = df.replace("", nan_value)
display(k)
k.dropna(how='all', axis=1, inplace=True)
display(k)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age  Department
0     Vipul    NaN    0         NaN
1    Ashish    NaN    0         NaN
2     Milan    NaN    0         NaN

  FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

In [58]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'], "Gender": ["", "", ""],"Age": [0, 0, 0]})
df['Department'] = np.nan
display(df)
nan_value = float("NaN")
df.replace(0, nan_value, inplace=True)
df.replace("", nan_value, inplace=True)
df.dropna(how='all', axis=1, inplace=True)
display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName
0     Vipul
1    Ashish
2     Milan

In [59]:
import pandas as pd
import numpy as np
data = {'Names': ['Gulshan', 'Shashank', 'Bablu', 'Abhishek', 'Anand', np.nan, 'Pratap'],
        'City': ['Delhi', 'Mumbai', 'Kolkata', 'Delhi', 'Chennai', 'Bangalore', 'Hyderabad']}

df = pd.DataFrame(data)
print(df)

# print(df['Names'].str.lower())
# print(df['Names'].str.upper())
# print(df['Names'].str.strip())
# df['Split_Names'] = df['Names'].str.split('a')
# print(df[['Names', 'Split_Names']])
# print(df['Names'].str.len())
# print("\nafter using cat:")
# print(df['Names'].str.cat(sep=', '))
# print(df['City'].str.get_dummies())
# print(df['Names'].str.startswith('G'))
# print(df['Names'].str.endswith('h'))
# print(df['Names'].str.replace('Gulshan', 'Gaurav'))
# print(df['Names'].str.repeat(2))
# print(df['Names'].str.count('a'))
# print(df['Names'].str.find('a'))
# print(df['Names'].str.findall('a'))
# print(df['Names'].str.islower())
# print(df['Names'].str.isupper())
# print(df['Names'].str.isnumeric())
#print(df['Names'].str.swapcase())

      Names       City
0   Gulshan      Delhi
1  Shashank     Mumbai
2     Bablu    Kolkata
3  Abhishek      Delhi
4     Anand    Chennai
5       NaN  Bangalore
6    Pratap  Hyderabad

In [60]:
import pandas as pd
data_frame = pd.DataFrame({
    'Name': ['Tom', 'Nick', 'Juli'],
    'Age': [10, '15', 14.8],
    'Salary': ['25000', 30000, '35000.50'],
    'Department': ['HR', 'IT', 'Finance']})
print("Original Data Types:")
print(data_frame.dtypes, '\n')
mixed_columns = []
for col in data_frame.columns:
    inferred = pd.api.types.infer_dtype(data_frame[col])
    if 'mixed' in inferred or inferred in ['string', 'mixed-integer']:
        mixed_columns.append(col)
print("Mixed or convertible columns detected:", mixed_columns, '\n')
for col in mixed_columns:
    data_frame[col] = pd.to_numeric(data_frame[col], errors='ignore')
print("Fixed Data Types:")
print(data_frame.dtypes, '\n')
for col in data_frame.columns:
    print(f"{col} → {pd.api.types.infer_dtype(data_frame[col])}")

Original Data Types:
Name             str
Age           object
Salary        object
Department       str
dtype: object

Mixed or convertible columns detected: ['Name', 'Age', 'Salary', 'Department']

ValueError: invalid error value specified